import logging
from typing import Dict, Any, List
import pandas as pd
import numpy as np

logger = logging.getLogger(__name__)

class PlanExecutor:
    """
    Executes a deterministic JSON plan generated by the LLM Planner against a Pandas DataFrame.
    Returns computed figures strictly without mutating the source dataset.
    """
    def __init__(self, df: pd.DataFrame):
        self.df = df
        
    def execute(self, plan: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute the plan and return a dictionary of computed results mapped by item id.
        """
        results = {}
        items = plan.get("items", [])
        
        for item in items:
            item_id = item.get("id")
            if not item_id:
                continue
                
            try:
                if item.get("type") == "kpi":
                    results[item_id] = self._execute_kpi(item)
                elif item.get("type") in ("visual", "table"):
                    results[item_id] = self._execute_visual(item)
                else:
                    logger.warning(f"Unsupported item type {item.get('type')} for item {item_id}")
            except Exception as e:
                logger.error(f"Error executing item {item_id}: {e}")
                results[item_id] = {"error": str(e)}
                
        return results
        
    def _apply_filters(self, df: pd.DataFrame, filters: List[Dict[str, Any]]) -> pd.DataFrame:
        if not filters:
            return df
        # Implementation of simple filters
        # To be expanded if needed
        return df

    def _aggregate(self, series: pd.Series, agg_func: str) -> float:
        if agg_func == "sum":
            return float(series.sum())
        elif agg_func == "avg":
            return float(series.mean())
        elif agg_func == "median":
            return float(series.median())
        elif agg_func == "min":
            return float(series.min())
        elif agg_func == "max":
            return float(series.max())
        elif agg_func == "count_rows":
            return int(len(series))
        elif agg_func == "count_non_null":
            return int(series.count())
        elif agg_func == "distinct_count":
            return int(series.nunique())
        return 0.0

    def _execute_kpi(self, item: Dict[str, Any]) -> Dict[str, Any]:
        metric = item.get("metric", {})
        col = metric.get("column")
        agg = metric.get("agg", "count_rows")
        
        if not col or col not in self.df.columns:
            raise ValueError(f"Column '{col}' not found in dataset")
            
        value = self._aggregate(self.df[col], agg)
        return {
            "value": value,
            "formatted_value": f"{value:,.2f}" if isinstance(value, float) else f"{value:,}",
            "title": item.get("title", f"{agg} of {col}")
        }
        
    def _execute_visual(self, item: Dict[str, Any]) -> Dict[str, Any]:
        chart_type = item.get("chart", "").lower()

        # ── Special path: scatter plots use RAW (un-aggregated) data ──────────
        # For scatter we need individual (x, y) points, not grouped aggregates.
        if chart_type == "scatter":
            return self._execute_scatter(item)

        # For visual and table, we generally have group_by (or x/series) and metrics (or y)
        group_cols = []
        metrics = []

        # Unify visual/table schema mapping - LLMs sometimes mix these up
        group_cols = list(item.get("group_by", []) or [])
        metrics = list(item.get("metrics", []) or [])

        # Also collect x and y if present
        x = item.get("x")
        if x and isinstance(x, dict) and x.get("column"):
            group_cols.append(x.get("column"))
        elif x and isinstance(x, str):
            group_cols.append(x)

        series_col = item.get("series")
        if series_col:
            if isinstance(series_col, dict) and series_col.get("column"):
                group_cols.append(series_col.get("column"))
            elif isinstance(series_col, str):
                group_cols.append(series_col)

        y = item.get("y", [])
        if isinstance(y, dict):
            metrics.append(y)
        elif isinstance(y, list):
            metrics.extend(y)

        # Filter valid columns
        group_cols = [c for c in group_cols if c and c in self.df.columns]
        
        if not group_cols and not metrics:
            raise ValueError("No valid grouping or metric columns provided.")
            
        # Handle time grain formatting if applicable (skip for now to keep simple)
            
        # Build agg dict - handling multiple metrics on same col
        # Use pd.NamedAgg for robust aggregation
        agg_kwargs = {}
        metric_col_names = []
        for i, m in enumerate(metrics):
            col = m.get("column")
            agg = m.get("agg", "sum")
            if col and col in self.df.columns:
                pd_agg = "count"
                if agg == "sum": pd_agg = "sum"
                elif agg == "avg": pd_agg = "mean"
                elif agg == "median": pd_agg = "median"
                elif agg == "min": pd_agg = "min"
                elif agg == "max": pd_agg = "max"
                elif agg == "distinct_count": pd_agg = "nunique"
                elif agg == "none" or agg == "raw": pd_agg = "first"
                
                out_col = f"{agg}_{col}"
                agg_kwargs[out_col] = pd.NamedAgg(column=col, aggfunc=pd_agg)
                metric_col_names.append(out_col)
                
        if not group_cols and agg_kwargs:
            # Global aggregation
            grouped = self.df.agg(**{k: (v.column, v.aggfunc) for k, v in agg_kwargs.items()}).to_frame().T
        elif group_cols and agg_kwargs:
            # Group and aggregate
            grouped = self.df.groupby(group_cols, dropna=False).agg(**agg_kwargs).reset_index()
        elif group_cols and not agg_kwargs:
            # Just group (e.g. distinct values)
            grouped = self.df[group_cols].drop_duplicates().reset_index(drop=True)
        else:
            grouped = pd.DataFrame()
        
        # Sort and Top N
        sort_cfg = item.get("sort")
        if sort_cfg:
            sort_by = sort_cfg.get("by")
            sort_dir = sort_cfg.get("dir", "desc")
            if sort_by in grouped.columns:
                grouped = grouped.sort_values(by=sort_by, ascending=(sort_dir == "asc"))
            else:
                # Try prefix search if sorting by just the raw column name
                for c in grouped.columns:
                    if c.endswith(f"_{sort_by}"):
                        grouped = grouped.sort_values(by=c, ascending=(sort_dir == "asc"))
                        break
                
        top_n = item.get("top_n")
        if top_n and isinstance(top_n, int) and top_n > 0:
            grouped = grouped.head(top_n)
            

        # Verify step
        warnings = []
        if grouped.empty:
            warnings.append("Result is empty.")
        elif grouped.isnull().all().all():
            warnings.append("Result contains only null values.")
            
        dataset = {
            "source": [grouped.columns.tolist()] + grouped.replace({np.nan: None}).values.tolist()
        }
        
        # Calculate Layout
        try:
            from bi_automation.charts.layout import compute_grid_margins
            x_labels = grouped[group_cols[0]].tolist() if group_cols else []
            layout_meta = compute_grid_margins(x_labels)
        except Exception:
            layout_meta = {}
        
        return {
            "dataset": dataset,
            "title": item.get("title", ""),
            "chart_type": item.get("chart", "bar") if item.get("type") == "visual" else "table",
            "warnings": warnings,
            "layout": layout_meta
        }

    def _execute_scatter(self, item: Dict[str, Any]) -> Dict[str, Any]:
        """Return raw (x, y) point data for scatter plots."""
        x_col = None
        y_col = None
        color_col = None

        x = item.get("x")
        if x and isinstance(x, dict):
            x_col = x.get("column")
        elif isinstance(x, str):
            x_col = x

        # y is an array of metric objects — take the first one
        y_list = item.get("y", []) or []
        if isinstance(y_list, dict):
            y_list = [y_list]
        if y_list:
            y_col = y_list[0].get("column")

        series = item.get("series")
        if series and isinstance(series, dict):
            color_col = series.get("column")

        # Validate that required columns exist
        missing = [c for c in [x_col, y_col, color_col] if c and c not in self.df.columns]
        if missing:
            raise ValueError(f"Scatter columns not found in dataset: {missing}")
        if not x_col or not y_col:
            raise ValueError("Scatter plot requires both x and y columns.")

        # Build dataset source: [header, ...rows]
        cols = [x_col, y_col]
        if color_col:
            cols.append(color_col)

        df_scatter = self.df[cols].dropna()

        warnings = []
        if df_scatter.empty:
            warnings.append("Scatter result is empty.")

        source = [cols] + df_scatter.replace({float('nan'): None}).values.tolist()

        return {
            "dataset": {"source": source},
            "title": item.get("title", f"{x_col} vs {y_col}"),
            "chart_type": "scatter",
            "x_col": x_col,
            "y_col": y_col,
            "color_col": color_col,
            "warnings": warnings,
            "layout": {}
        }

